causing an error on yarn start b/c of bad version given
fixes this error: this.physicsEngine = new PhysicsEngine();
TypeError: PhysicsEngine is not a constructor
appeared while doing pong tutorial. Would work from pull pong branch code.